# Generated by Django 5.2.7 on 2025-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="access_token",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
