# Generated by Django 5.2.7 on 2026-01-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="refresh_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="spotify_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="token_expires",
        ),
    ]
