# Generated by Django 5.2.7 on 2025-10-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="artist_found",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="title_found",
            field=models.BooleanField(default=False),
        ),
    ]
