# Generated by Django 5.2.7 on 2025-10-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
    ]
