# Generated by Django 5.2.7 on 2025-11-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_song_popularity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="artist_found",
        ),
        migrations.RemoveField(
            model_name="question",
            name="title_found",
        ),
    ]
