# Generated by Django 5.2.7 on 2026-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_playlist_users_alter_playlist_songs"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="preview_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
