# Generated by Django 5.2.7 on 2026-01-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_populate_song_preview_urla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="preview_url",
            field=models.URLField(max_length=500),
        ),
    ]
